banner:
  enable: true
  title: åŒ…å­å›çš„å°ç«™
  src: /js/ui/banner.js
  border: true
  cloud:
    enable: true
    color: "white"
  go_down:
    enable: true
    icon: icon-arrow-down-s-line
avatar:
  enable: true
  url: /images/logo.png
  rounded: true
  opacity: 1
  mickey_mouse: false
  status:
    enable: true
    emoji: ğŸ˜­
    message: ä¸æƒ³ä¸Šå­¦
reward:
  enable: true
  icon: icon-hand-coin-line
  comment: I'm so cute. Please give me money.
  # url: https://github.com/YunYouJun/yunyoujun.github.io/issues/96
  #é—®é¢˜ï¼šèµèµæ¢æˆè‡ªå·±çš„äºŒç»´ç çš„è¯å›¾ç‰‡é“¾æ¥æ€ä¹ˆå†™ï¼Œç›´æ¥å†™ç›¸å¯¹è·¯å¾„+cdnè¿˜æ˜¯ç›¸å¯¹è·¯å¾„
  methods:
    - name: å¾®ä¿¡æ”¯ä»˜
      path: /images/money.jpg
      color: "#2DC100"
      icon: icon-wechat-pay-line
beian:
    enable: false
    icp: ç²¤ICPå¤‡2020102011å·
    
social:
  - name: E-Mail
    link: mailto:sfa_freshman@qq.com
    icon: icon-mail-line
    color: "#8E71C1"
  - name: å¾®ä¿¡
    link: /images/qrcode.jpg
    icon: icon-wechat-2-line
    color: "#1AAD19"
mode: auto
menu:
  home:
    path: /
    icon: icon-home-4-line
  list:
    - type: archives
      path: /archives/
      icon: icon-archive-line
    - type: categories
      path: /categories/
      icon: icon-folder-2-line
    - type: tags
      path: /tags/
      icon: icon-price-tag-3-line
  custom:
    title: æ‹œè¯»
    path: https://darksheep404/categories/%E5%88%86%E4%BA%AB/
    icon: icon-settings-line
##ä¸å±•ç¤ºæœ«å°¾ç‰ˆæƒä¿¡æ¯
creative_commons:
  license: by-nc-sa
  post: false
  language: deed.zh
  clipboard: false
footer:
  live_time:
    enable: true
    prefix: æœ¬åšå®¢å·²èŒèŒå“’åœ°è¿è¡Œ
    suffix: (â—'â—¡'â—)
    start_time: "2020-10-12T00:00:00"

comment:
  enable: true
  icon: icon-chat-3-line
  tips:
    - æ¬¢è¿æ¥è¸©ä¸€è¸©
  candidates:
    - valine
  #   - utterances
# GitHub Issues Link Button
# https://help.github.com/en/github/searching-for-information-on-github/searching-issues-and-pull-requests
# github_issues:
#   enable: true
#   username: SFAfreshman
#   repository: sfafreshman.github.io
#   filters: is:issue
valine:
  enable: true
  appId: K8sNkb431hIYsYIJt5cY5ej8-gzGzoHsz
  appKey: lDlaLdG4bnwWtiHoTg9hxfR8
  placeholder: æœ•æ›° # comment box placeholder
  avatar: # gravatar style
  meta:
    - nick
    - mail
    - link
  pageSize: 10 # pagination size
  # lang: zh-CN
  enableQQ: true
codeblock:
  copy_btn: true
  prismjs:
    light: tomorrow
    dark: tomorrow
engine_search:
  enable: true
  href: "https://www.google.com/search?q=site:"
  # href: "https://www.baidu.com/s?wd=site:"
  # href: "https://www.bing.com/search?q=site:"
  domain: darksheep.xyz
favicon: /favicon.ico